apiVersion: v2
name: seaweedfs
description: SeaweedFS — S3-compatible storage for Flink checkpoints (local dev)
version: 0.1.0
dependencies:
  - name: seaweedfs
    version: "*"
    repository: "https://MathTrail.github.io/charts/charts"
