apiVersion: v2
name: redpanda-console
description: Redpanda Console — Kafka UI for local development observability
version: 0.1.0
dependencies:
  - name: console
    version: "*"
    repository: "https://MathTrail.github.io/charts/charts"
