apiVersion: v2
name: kafka-ui
description: kafka-ui — Kafka UI for local development observability
version: 0.1.0
dependencies:
  - name: kafka-ui
    version: "*"
    repository: "https://MathTrail.github.io/charts/charts"
