kafka-ui:
  envs:
    config:
      SERVER_SERVLET_CONTEXT_PATH: /observability/kafka-ui
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=50.0 -XX:MaxMetaspaceSize=150m -XX:+UseContainerSupport"

  yamlApplicationConfig:
    kafka:
      clusters:
        - name: local
          bootstrapServers: kafka-kafka-bootstrap:9092
          schemaRegistry: http://mathtrail-apicurio-apicurio-registry:8080/apis/ccompat/v7
          kafkaConnect:
            - name: debezium
              address: http://debezium-connect-api:8083

  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 768Mi
      cpu: 500m

  service:
    type: ClusterIP
    port: 8080
