kafka-ui:
  yamlApplicationConfig:
    server:
      servlet:
        context-path: /observability/kafka-ui
    management:
      server:
        port: 8081
    kafka:
      clusters:
        - name: local
          bootstrapServers: kafka-kafka-bootstrap:9092
          schemaRegistry: http://mathtrail-apicurio-apicurio-registry:8080/apis/ccompat/v6
          kafkaConnect:
            - name: debezium
              address: http://debezium-connect-api:8083

  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8081
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8081

  resources:
    requests:
      memory: 384Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

  service:
    type: ClusterIP
    port: 8080
