apiVersion: v2
name: minio-local
description: MinIO local wrapper for MathTrail streaming namespace
type: application
version: 0.1.0
dependencies:
  - name: minio
    version: "*"
    repository: "https://MathTrail.github.io/charts/charts"
