apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mathtrail-flink
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mathtrail
  source:
    repoURL: https://github.com/MathTrail/infra-streaming
    targetRevision: main
    path: infra/local/helm/flink
  destination:
    server: https://kubernetes.default.svc
    namespace: mathtrail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
