apiVersion: v1
kind: Service
metadata:
  # Named postgres-pgbouncer so services can use DB_HOST=postgres-pgbouncer
  name: postgres-pgbouncer
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/part-of: mathtrail
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/name: pgbouncer
  ports:
    - name: pgbouncer
      port: 6432
      targetPort: 6432
