apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-root-creds
spec:
  type: kv-v2
  mount: secret
  path: local/streaming-minio-root
  destination:
    name: minio-root-creds
    create: true
  refreshAfter: 1h
  vaultAuthRef: minio-vault-auth
