# MinIO S3 credentials for RisingWave state storage
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: risingwave-minio-creds
spec:
  type: kv-v2
  mount: secret
  path: local/streaming-minio-risingwave
  destination:
    name: risingwave-minio-creds
    create: true
  refreshAfter: 1h
  vaultAuthRef: risingwave-vault-auth
