apiVersion: v1
kind: Secret
metadata:
  name: minio-root-creds
  namespace: streaming
type: Opaque
stringData:
  rootUser: {{ .Values.minio.rootUser }}
  rootPassword: {{ .Values.minio.rootPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: risingwave-minio-creds
  namespace: streaming
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.risingwave.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.risingwave.secretAccessKey }}
