risingwave:
  fullnameOverride: "risingwave-frontend"
  service:
    port: 4566

  metaStore:
    sqlite:
      enabled: true
      path: /var/risingwave/meta/risingwave.db

  metaComponent:
    extraVolumes:
      - name: meta-sqlite
        persistentVolumeClaim:
          claimName: risingwave-meta-sqlite
    extraVolumeMounts:
      - name: meta-sqlite
        mountPath: /var/risingwave/meta

  stateStore:
    s3:
      enabled: true
      endpoint: "http://streaming-minio:9000"
      bucket: "risingwave-data"
      region: "us-east-1"
      forcePathStyle: true
      authentication:
        existingSecretName: "risingwave-minio-creds"
